name: Build and Push Docker image to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR 
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 442222453508.dkr.ecr.ap-south-1.amazonaws.com
      
      - name: Build Docker image
        run: docker build -t python-app-repo:${{ github.sha }} .

      - name: Tag Docker image
        run: docker tag python-app-repo:${{ github.sha }} 442222453508.dkr.ecr.ap-south-1.amazonaws.com/python-app-repo:${{ github.sha }}
     
      - name: Push Docker image to ECR
        run: docker push 442222453508.dkr.ecr.ap-south-1.amazonaws.com/python-app-repo:${{ github.sha }}

      - name: Get latest ECR image tag
        id: ecr-get-latest-tag
        run: |
          echo "::set-output name=latest_tag::$(aws ecr describe-images --repository-name python-app-repo --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text)"
     
      - name: Update values.yml file
        run: |
          git clone https://github.com/kunal-154/helmchart-repo.git
          sed -i "s/tag: .*/tag: ${{ steps.ecr-get-latest-tag.outputs.latest_tag }}/" helmchart-repo/app/pyValues.yaml
     
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
           source-directory: 'helmchart-repo'
           destination-github-username: 'kunal-154'
           destination-repository-name: 'helmchart-repo'
           user-email: kunalgupta154@gmail.com
           target-branch: main
